
FROM nvcr.io/nvidia/cuda:11.8.0-base-ubuntu22.04

ENV PYTHON_VERSION="3.10"
ENV TORCH_VERSION="2.0.0+cu118"
ENV TORCH_VISION_VERSION="0.15.1+cu118"
ARG OPENCV_VERSION==4.10.0.84

USER root
WORKDIR /workspace

ARG DEBIAN_FRONTEND=noninteractive

RUN  apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        git \
        wget \
        unzip \
        nano \
        openssh-client \
        gnupg \
        cmake \
        libopencv-dev \
        libprotobuf-dev \
        protobuf-compiler \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean

ENV CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# install python
RUN apt-get update && \
    apt-get install software-properties-common gcc --no-install-recommends --assume-yes && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install python${PYTHON_VERSION} python${PYTHON_VERSION}-distutils python3-pip python3-setuptools python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv --no-install-recommends --assume-yes
RUN python${PYTHON_VERSION} -m venv /home/venv
ENV PATH=/home/venv/bin:$PATH

RUN python -m pip install --no-cache-dir  opencv-python-headless==${OPENCV_VERSION} && \
    python -m pip install --no-cache-dir torch==${TORCH_VERSION} torchvision==${TORCH_VISION_VERSION} -f https://download.pytorch.org/whl/torch_stable.html && \
    python -m pip install --upgrade pip setuptools wheel

# One of the links is set wrong in pytorch...
# https://discuss.pytorch.org/t/could-not-load-library-libcudnn-cnn-infer-so-8/175139/12
RUN ln -s /home/venv/lib/python3.10/site-packages/torch/lib/libnvrtc-672ee683.so.11.2 /home/venv/lib/python3.10/site-packages/torch/lib/libnvrtc.so

# setting up container user with sudo access rights (not default)
ARG USERNAME=containerUser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

RUN chown -R containerUser:containerUser /home/venv
