
FROM nvcr.io/nvidia/cuda:12.1.0-base-ubuntu22.04

ENV PYTHON_VERSION="3.12"
ENV TORCH_VERSION="2.3.1+cu121"
ENV TORCH_VISION_VERSION="0.18.1+cu121"
ARG OPENCV_VERSION==4.10.0.84

USER root
ARG DEBIAN_FRONTEND=noninteractive

RUN  apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        git \
        wget \
        unzip \
        nano \
        openssh-client \
        gnupg \
        cmake \
        libopencv-dev \
        libprotobuf-dev \
        protobuf-compiler \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean

ENV CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# install python
RUN apt-get update && \
    apt-get install software-properties-common gcc --no-install-recommends --assume-yes && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv python3-pip python3-full --no-install-recommends --assume-yes


# setting up container user with sudo access rights (not default)
ARG USERNAME=containerUser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER ${USERNAME}

RUN python${PYTHON_VERSION} -m venv /home/${USERNAME}/venv
ENV PATH=/home/${USERNAME}/venv/bin:$PATH
RUN python -m pip install --no-cache-dir  opencv-python-headless==${OPENCV_VERSION} && \
    python -m pip install --no-cache-dir torch==${TORCH_VERSION} torchvision==${TORCH_VISION_VERSION} -f https://download.pytorch.org/whl/torch_stable.html && \
    python -m pip install --upgrade pip setuptools wheel

WORKDIR /workspace

