
################################################################################
# Container description & use case...
#
# Build:
#   docker build -t py312_cuda126_cudnn9_ubuntu24 -f Dockerfile_py312_cuda126_cudnn9_ubuntu24 .
# Run as devcontainer:
#   docker run -it --rm --gpus all -v ${PWD}:/project -w /project --network=host py312_cuda126_cudnn9_ubuntu24
# To jump into this container if already running, use
#   docker exec -it py312_cuda126_cudnn9_ubuntu24 bash
################################################################################

# ubuntu24 comments
# Updated python install to avoid deadsnakes and use actual ubuntu package repo
# updated user credential code to work on 24.04
FROM nvcr.io/nvidia/cuda:12.6.1-cudnn-devel-ubuntu24.04

ENV PYTHON_VERSION="3.12"
ENV CUDA_VENV="cu126"
ENV TORCH_VERSION="2.8.0"
ENV TORCH_VISION_VERSION="0.23.0"
 
USER root
ARG DEBIAN_FRONTEND=noninteractive
 
RUN  apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        git \
        wget \
        unzip \
        nano \
        openssh-client \
        gnupg \
        cmake \
        libopencv-dev \
        libprotobuf-dev \
        protobuf-compiler \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean
 
ENV CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

################################### python ###################################
RUN apt-get update && \
    apt-get install software-properties-common gcc --no-install-recommends --assume-yes
RUN apt-get update && \
    apt-get install software-properties-common gcc python${PYTHON_VERSION} python3-pip python3-setuptools python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv --no-install-recommends --assume-yes

################################### sudo rights ###################################
# setting up container user with sudo access rights (not default)
RUN touch /var/mail/ubuntu && chown ubuntu /var/mail/ubuntu && userdel -r ubuntu
ARG USERNAME=containerUser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
#RUN chown -R containerUser:containerUser /home/venv
## ask kevin why containerUser did not work
RUN mkdir -p /home/venv && chown -R ${USER_UID}:${USER_GID} /home/venv
USER ${USERNAME}

################################### venv/torch ###################################
RUN python${PYTHON_VERSION} -m venv /home/venv
ENV PATH=/home/venv/bin:$PATH
 
RUN python -m pip install --no-cache-dir torch==${TORCH_VERSION} torchvision==${TORCH_VISION_VERSION} -f https://download.pytorch.org/whl/${CUDA_VENV}/ && \
    python -m pip install --upgrade pip setuptools wheel


WORKDIR /workspace

################################### custom packages ###################################
