################################################################################
# Container description & use case... 
# nvidia driver version CUDA compatability > 530.xx: see https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/
#
# Build:
#   docker build -t py312_cuda121_ubuntu22 -f Dockerfile_py312_cuda121_ubuntu22 .
# Run as devcontainer:
#   docker run -it --rm --gpus all -v ${PWD}:/project -w /project --network=host py312_cuda121_ubuntu22
# To jump into this container if already running, use
#   docker exec -it py312_cuda121_ubuntu22 bash
################################################################################

FROM nvcr.io/nvidia/cuda:12.1.0-base-ubuntu22.04

ENV PYTHON_VERSION="3.12"
ENV CUDA_VENV="cu121"
ENV TORCH_VERSION="2.3.1"
ENV TORCH_VISION_VERSION="0.18.1"

USER root
ARG DEBIAN_FRONTEND=noninteractive

RUN  apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        ca-certificates \
        git \
        wget \
        unzip \
        nano \
        openssh-client \
        gnupg \
        cmake \
        libopencv-dev \
        libprotobuf-dev \
        protobuf-compiler \
        && rm -rf /var/lib/apt/lists/* \
        && apt-get clean

ENV CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH

################################### python ###################################

RUN apt-get update && \
    apt-get install software-properties-common gcc --no-install-recommends --assume-yes && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv python3-pip python3-full --no-install-recommends --assume-yes

################################### sudo rights ###################################
# setting up container user with sudo access rights (not default)

ARG USERNAME=containerUser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER ${USERNAME}

################################### venv/torch ###################################

RUN python${PYTHON_VERSION} -m venv /home/${USERNAME}/venv
ENV PATH=/home/${USERNAME}/venv/bin:$PATH

RUN python -m pip install --no-cache-dir torch==${TORCH_VERSION} torchvision==${TORCH_VISION_VERSION} -f https://download.pytorch.org/whl/${CUDA_VENV}/ && \
    python -m pip install --upgrade pip setuptools wheel

################################### workspace ###################################
RUN mkdir /workdir
RUN chown ${USERNAME}:${USER_GID} /workdir
WORKDIR /workspace

################################### custom packages ###################################
